CHANGELOG.md, EXTENSION.md, README.md, package.json
Prep for release, so pulling together docs changes including:
* adding quick fixes as a sublist to the readme.d and extension.md
* include v0.1.0 in the `CHANGELOG.md`
=> docs: add quickfixes to feature lists

server/src/parser/analyzer/index.ts
Parser errors are to be expected in a code file that is being constantly added to by the user. We suppress at the closest point to parsing to avoid catching other errors.
Fixes https://github.com/NomicFoundation/hardhat-vscode/issues/90
=> chore(validation): suppress logging parser errors

.changeset/quick-numbers-sleep.md, server/package.json, server/src/analytics/GoogleAnalytics.ts, server/src/analytics/types.ts, server/src/index.ts, server/src/parser/services/codeactions/onCodeAction.ts, server/src/parser/services/validation/SolidityValidation.ts, server/src/server.ts, server/src/telemetry/SentryTelemetry.ts, server/src/telemetry/types.ts, server/src/types.ts, server/test/helpers/setupMockAnalytics.ts, server/test/helpers/setupMockTelemetry.ts, server/yarn.lock
Sentry has added extensive performance tracking. We are currently hacking GA to provide a rough version. We should switch to sentry to take advantage of its inbuilt sampling and richer features. This involves:
Linear: HHVSC-119
=> switch performance telemetry to sentry

.changeset/shiny-spoons-reply.md, EXTENSION.md, README.md, server/src/parser/analyzer/utils/typeGuards.ts, server/src/parser/services/hover/onHover.ts, server/src/parser/services/hover/utils/astToText.ts, server/src/parser/services/hover/utils/textTohover.ts, server/src/server.ts, server/test/helpers/setupMockConnection.ts, server/test/helpers/setupMockLanguageServer.ts, server/test/parser/services/hover/assertOnServerHover.ts, server/test/parser/services/hover/error.ts, server/test/parser/services/hover/event.ts, server/test/parser/services/hover/function.ts, server/test/parser/services/hover/identifier.ts, server/test/parser/services/hover/testData/Error.sol, server/test/parser/services/hover/testData/Event.sol, server/test/parser/services/hover/testData/Function.sol, server/test/parser/services/hover/testData/Identifier.sol, test/integration/tests/configuration/configuration.test.json
This implements the `onHover` functionality of the LSP.
It does this for identifiers in local functions, and will give type and other information from local variables, parameters and state variables.
It adds hover for functions invocations, events and errors as well.
Comments are not included in the display (they are not in the ast).
Relates to https://github.com/NomicFoundation/hardhat-vscode/issues/62
* we on display hovers for variable accesses, function calls, event emits and error reverts
* we do not display the related comments (natspec or otherwise)
* display is conditional on the parser (if it errors, no hover)
Linear: HHVSC-49
=> feat(hover): add hover text

.changeset/strong-hats-deny.md, server/src/parser/services/validation/HardhatProcess.ts
To kill the child compilation process we pass in the pid. The docs suggest we can leave it and take the default signal of `SIGTERM`.
Fixes #89.
I have done a round of manual tests. Validation appears unaffected.
Linear: HHVSC-111
=> fix: stop passing pid to kill

.changeset/fair-emus-tap.md, server/src/compilerDiagnostics/diagnostics/parsing/parseContractDefinition.ts, server/src/compilerDiagnostics/diagnostics/parsing/parseFunctionDefinition.ts
Parser errors on changing code are to be expected, so lets not report them via telemetry.
Linear: HHVSC-132
=> fix(quickfixes): swallow parser errors

server/src/parser/common/utils/index.ts
Stop import completion throwing on failed `isNodePosition` lookup.
Fixes #143.
Linear: HHVSC-129
=> fix: catch for undefined in isNodePosition

.changeset/heavy-lamps-attack.md, server/src/parser/index.ts, server/src/parser/services/validation/DiagnosticConverter.ts, server/src/parser/services/validation/SolidityValidation.ts
We group and filter hh errors that are displayed as diagnostics. We were
getting exceptions when a hh error came through with no attached source
location as this was used for the filtering and grouping.
Instead we will let hh errors without source locations pass through, but
send the error message to sentry (so we can dig in with more info).
Fixes #147.
Linear: HHVSC-133
=> fix: allow hh errors with no source location

.changeset/heavy-lamps-attack.md, .changeset/tall-ghosts-push.md, client/.eslintrc.js, client/package.json, client/src/extension.ts, client/src/formatter/index.ts, client/src/popups/showAnalyticsAllowPopup.ts, client/src/popups/showFileIndexingProgress.ts, client/src/popups/warnOnOtherSolidityExtensions.ts, client/src/setup/setupExtensionState.ts, client/src/setup/setupFormatterHook.ts, client/src/setup/setupLanguageServerHooks.ts, client/src/telemetry/SentryClientTelemetry.ts, client/src/telemetry/types.ts, client/src/types.ts, client/src/utils/Logger.ts, client/src/utils/getOuterMostWorkspaceFolder.ts, client/src/utils/getUnsavedDocuments.ts, client/yarn.lock, package.json, server/src/telemetry/SentryTelemetry.ts, tsconfig.json
We have reports of issues with formatting on linux. For some users the issue with a misconfiguration on the formatter setting inside of hardhat vscode, for others we just don't know.
This PR does two things:
* remove the formatter setting as unnecessary
* improve logging around formatting within the client
To do the above, sentry had to be setup and configured for the client part of the extension.
Linear: HHVSC-128 HHVSC-124
=> chore: improve clientside formatting

.changeset/wild-paws-travel.md, client/src/telemetry/SentryClientTelemetry.ts, server/src/index.ts, server/src/telemetry/SentryServerTelemetry.ts
By default Sentry hooks into the uncaught exception handler and reports
all unhandled exceptions. The extension is run within the extension host
and adding the uncaught exception handler give all unhandled exceptions
across all extensions.
To stop that reporting we turn off the global exception handler.
Fixes #156.
Linear: HHVSC-139
=> chore(telemetry): turn off client uncaught exceptions

syntaxes/solidity.json
---
Implements the feature outlined in issue https://github.com/NomicFoundation/hardhat-vscode/issues/161.
The regex pattern used for matching custom tags is based on the description provided in [Solidity documentation](https://docs.soliditylang.org/en/v0.8.13/natspec-format.html#tags):
> Custom tags start with @custom: and must be followed by one or more lowercase letters or hyphens. It cannot start with a hyphen however. They can be used everywhere and are part of the developer documentation.
=> feat(syntaxes): add support for custom NatSpec tags

syntaxes/solidity.json
Include the comment pattern in both enum declaration and function argument lists and modifier lists.
Fixes #165.
Linear: HHVSC-143
=> feat(syntax): allow comments in enums

package.json
extensionKind is a property in the extension manifest. It allows extensions to specify a preferred running location. That can be the machine that has the workspace (workspace) or the user interface (ui). If an extension can run on both, it can specify an order of preference. 
[see https://code.visualstudio.com/api/advanced-topics/extension-host#preferred-extension-location](https://code.visualstudio.com/api/advanced-topics/extension-host#preferred-extension-location)
---
=> feat(vscode): extenstionKind

server/src/services/validation/SolidityValidation.ts
Change the error log to a trace in validation. We expect non-hh files to not be
validated. It is not an error, though we probably want logging to report
it if we are doing debugging.
Fixes #172
Linear: HHVSC-146
=> chore(server): suppress val error in none hh files

server/src/services/completion/arrayCompletions.ts, server/src/services/completion/onCompletion.ts, server/test/services/completion/completion.ts, server/test/services/completion/testData/MemberAccessArrays.sol, server/test/services/navigation/testData/TypeDefinition.sol, server/test/services/navigation/typeDefinition.ts
If a variable/member access is an array, show the `array` members as completions. Specifically show `length`, `pop` and `push` based on [the solidity docs](https://docs.soliditylang.org/en/latest/types.html?highlight=array#array-members).
Fixes #179
=> fix(completion): provide array completions

package.json
The language server requires access to the file-system so needs to run
in an env that supports those calls.
Fixes #182
Linear: HHVSC-152
=> fix: update extension kind to `workspace`

server/src/services/rename/onRename.ts, server/test/services/rename/rename.ts, server/test/services/rename/testData/ContractRename.sol
When calculating reference nodes for a rename, exclude dead nodes.
Before this fix, it was possible to get duplicates for workspace edits, which would both be applied, leading to a rename of `Auth` to `Auth2` becoming:
```solidity
constructor() {
_auth = new Auth22(msg.sender);
}
```
=> fix: rename duplication

CHANGELOG.md, package.json, server/src/services/completion/arrayCompletions.ts, server/src/services/completion/onCompletion.ts, server/src/services/rename/onRename.ts, server/test/services/completion/completion.ts, server/test/services/completion/testData/MemberAccessArrays.sol, server/test/services/navigation/testData/TypeDefinition.sol, server/test/services/navigation/typeDefinition.ts, server/test/services/rename/rename.ts, server/test/services/rename/testData/ContractRename.sol
- Include completions for arrays for variables and member accesses ([#179](https://github.com/NomicFoundation/hardhat-vscode/issues/179))
- Change extensionKind to workspace only, to ensure always has access to workspace files ([#182](https://github.com/NomicFoundation/hardhat-vscode/issues/182))
- Fix in renames to ignore dead nodes in the ast when calculating updates ([#184](https://github.com/NomicFoundation/hardhat-vscode/pull/184))
=> release: 2022-05-10

client/src/telemetry/SentryClientTelemetry.ts, server/src/telemetry/SentryServerTelemetry.ts
We have enough users that we are running up against our transaction limits in Sentry. So we are reducing the sample rate from 1 in 100 to 1 in 1000. This will affect our performance tracking, not our exception capturing.
=> chore(telemetry): decrease the sampling

server/src/services/codeactions/onCodeAction.ts, server/src/services/completion/onCompletion.ts, server/src/services/initialization/onInitialized.ts, server/src/telemetry/SentryServerTelemetry.ts, server/src/telemetry/types.ts, server/src/utils/onCommand.ts, server/test/helpers/setupMockTelemetry.ts, server/test/services/completion/imports.ts
The telemetry tracking method now captures exceptions on action, and records failure of the transaction (for our telemetry tracking). The action can also return a failure status directly.
We leverage this new telemetry feature to no longer send command fails due to an analyzed file, instead we mark the command as a failed command (and so track it through our performance telemetry).
This should allow us to track the quality of lsp commands while reducing the number of exceptions sent to telemetry.
=> chore(telemetry): track transaction success/failure

server/src/services/documents/onDidChangeWatchedFiles.ts, server/test/helpers/setupMockTelemetry.ts, server/test/services/documents/onDidChangeWatchedFiles.ts, server/test/services/validation/validation.ts
On a config change, the worker is restarted. If the worker for the config can't be found, we should log and return rather than exceptioning on the undefined worker process.
Fixes #193
=> fix(validation): gracefully report no worker

server/src/services/validation/worker/build/buildInputsToSolc.ts, server/src/services/validation/worker/build/solcCompile.ts, server/src/services/validation/worker/build/solcOutputToCompleteMessage.ts, server/src/types.ts, server/src/utils/Logger.ts, server/test/services/validation/worker.ts
For validation we do not need solc code generation, just errors and warnings. Nor do we need optimization. We override these setting no matter what the user has in their `hardhat.config.{ts,js}`.
Other settings are passed on without change.
=> feat: enforce input settings for validation

.vscodeignore, client/src/setup/setupLanguageServerHooks.ts, package.json, scripts/bundle.js, server/package.json, server/src/services/documents/attachDocumentHooks.ts, server/src/services/documents/onDidChangeContent.ts, server/src/services/documents/onDidChangeWatchedFiles.ts, server/src/services/rename/onRename.ts, server/src/services/validation/HardhatWorker.ts, server/src/services/validation/invalidateWorkerPreprocessCache.ts, server/src/services/validation/restartWorker.ts, server/src/services/validation/worker/build/buildInputsToSolc.ts, server/src/services/validation/worker/build/hardhatBuild.ts, server/src/services/validation/worker/build/solcOutputToCompleteMessage.ts, server/src/services/validation/worker/dispatch.ts, server/src/services/validation/worker/initialiseWorkerState.ts, server/src/services/validation/worker/setupWorkerLogger.ts, server/src/services/validation/worker/utils/clearPreprocessingCacheState.ts, server/src/types.ts, server/test/helpers/setupMockCompilerProcessFactory.ts, server/test/services/documents/onDidChangeWatchedFiles.ts, server/test/services/documents/tracking.ts, server/test/services/validation/worker.ts, server/yarn.lock
Within the worker (`workerState`) we retain the last input to solc calculated by the preprocessing steps. If the same uri with the same solc version and imports comes in again, we reuse the same input with an updated content for the one changed file.
This gives a performance improvement (the preprocessing is the larger part of validation in big codebases) for the most common case which is lots of changes in a single file.
Fixes #55
=> feat(validation): cache solc input

server/src/services/validation/worker/build/buildInputsToSolc.ts, server/src/services/validation/worker/initialiseWorkerState.ts, server/src/types.ts, server/test/services/validation/worker.ts
We override hardhat read file task, to read from the passed in open documents array of the build job. This fixes the import line issue with import line errors being based on the disk version rather than the open editor version.
Fixes #201
=> fix(validation): use open docs in preprocessing steps

CHANGELOG.md, README.md
We want to use the same way of referring to the extension everywhere, the docs have been updated from `Hardhat VSCode` to `**Hardhat for Visual Studio Code**`.
=> docs: remove usages of hardhat vscode

CHANGELOG.md, package.json, server/src/services/validation/HardhatWorker.ts
- Fix to restart validation processes on unexpected exits ([#209](https://github.com/NomicFoundation/hardhat-vscode/pull/209))
=> release:2022-07-18

language-configuration.json, test/integration/client.ts, test/integration/common/assertLspCommand.ts, test/integration/helpers/assertions.ts, test/integration/helpers/commands.ts, test/integration/helpers/docPaths.ts, test/integration/helpers/files.ts, test/integration/helpers/joinLines.ts, test/integration/helpers/misc.ts, test/integration/helpers/sleep.ts, test/integration/tests/definition/definition.test.ts, test/integration/tests/implementation/implementation.test.ts, test/integration/tests/language-configuration/onEnterRules.test.ts, test/integration/tests/references/references.test.ts, test/integration/tests/rename/rename.test.ts, test/integration/tests/typedefinition/typedefinition.test.ts
When using multiline comments, intermediate stars (*) are added automatically with correct indentation.
Closes #75
=> feat:  Support intermediary stars in block comments #75

server/src/services/validation/validate.ts, server/test/services/validation/validation.ts
Solc can report warnings/errors during validation that are against files other than the current open editor file (i.e. an error in a dependency). We where ignoring those dependency errors, but not clearing any previous
diagnostics on the open editor (which had no warnings/errors against it).
We now treat a validation fail with every warning/error in files other than the open editor as the equivalent of a validation pass on the open editor; we clear any previous diagnostics and report validation success against the file.
Fixes #221
=> fix(validation): clear when errors in other file

server/src/services/completion/defaultCompletion.ts, server/src/services/completion/onCompletion.ts, server/test/services/completion/completion.ts, server/test/services/completion/testData/GlobalVariables.sol
I went with a simple approach of adding the address methods directly on the `msg.sender` global identifier. I think we don't have address type completions in place. 
Please advice on the approach I took for being able to identify the `msg.sender` node, since the existing code would only work for finding single word orphan nodes for globals (e.g. `msg`, `tx`, `abi`). But it wouldn't work for a chain of member access (e.g. `foo.bar.baz`. I did my best to avoid interfering with the existing logic for orphan nodes.
A possible improvement would be to move the logic from `getLastExpressionNode` and `getFullName` from the service module to the node classes themselves (`MemberAccessNode`, `IdentifierNode`, `Node`), but I'm not sure if I have the freedom to do that.
Closes #202
=> feat: Completions for msg.sender (#202)

server/src/compilerDiagnostics/compilerDiagnostics.ts, server/src/compilerDiagnostics/diagnostics/SpecifyCompilerVersion.ts, server/src/services/documents/onDidChangeContent.ts, server/test/services/codeactions/specifyCompilerVersion.ts, server/test/services/codeactions/testData/SpecifyCompilerVersion.sol
Closes #25 
We make use of the solc warning for code 3420 (Source file does not specify required compiler version! Consider adding "pragma solidity ^0.8.7;") to extract the pragma line and insert it into the contract code.
=> feat: Quickfix for specifying compiler version

CHANGELOG.md, client/package.json, client/yarn.lock, package.json, server/package.json, server/src/compilerDiagnostics/compilerDiagnostics.ts, server/src/compilerDiagnostics/diagnostics/SpecifyCompilerVersion.ts, server/src/services/completion/defaultCompletion.ts, server/src/services/completion/onCompletion.ts, server/src/services/documents/onDidChangeContent.ts, server/src/services/validation/validate.ts, server/test/services/codeactions/specifyCompilerVersion.ts, server/test/services/codeactions/testData/SpecifyCompilerVersion.sol, server/test/services/completion/completion.ts, server/test/services/completion/testData/GlobalVariables.sol, server/test/services/validation/validation.ts, server/yarn.lock
- Added Quickfix for missing solidity compiler version pragma ([#25](https://github.com/NomicFoundation/hardhat-vscode/issues/25))
- Fix to validation to clear diagnostics when all warnings/errors are in files other than the open editor ([#221](https://github.com/NomicFoundation/hardhat-vscode/issues/221))
- Fix to formatting to not remove semi-colons on virtual modifiers ([#219](https://github.com/NomicFoundation/hardhat-vscode/issues/219))
- Fix to completions for `msg.sender` ([#202](https://github.com/NomicFoundation/hardhat-vscode/issues/202))
=> release:2022-08-11

docs/publish-extension.md
The publish instructions need updated to follow acutal usage and include deploying to open vsix.
=> docs: update publish instructions

client/src/popups/setupIndexingHooks.ts, server/src/services/initialization/onInitialized.ts, server/src/services/validation/HardhatWorker.ts, server/src/services/validation/compilerProcessFactory.ts, server/src/types.ts, server/test/services/validation/hardhatWorker.ts
Closes #229
Open files were being sent for validation before the validation workers were operational.
I introduced a new notification sent from the server for each validation worker that got up and running. The client will revalidate files within the project associated to each given worker.
=> fix: Open files not being analyzed because of validator starting

client/src/languageitems/hardhatProject.ts, client/src/popups/setupValidationJobHooks.ts, client/src/utils/files.ts, server/src/services/validation/validate.ts, server/src/types.ts, server/test/services/validation/validation.ts, test/integration/helpers/editor.ts
Added a link on the status item linking to the file that is importing a non existent file.
The way hardhat works, is that the project cannot be compiled if the dependency graph cannot be built successfully (e.g. on an incorrect import). The extension already shows a diagnostic if the import line is on the current file, but just a status item if the error is on another file. This change adds a link to that status item
Closes #238
=> chore: link to error file on status item (#238)

package.json
As we add more non-hardhat features, we want to emphasize that this extension is focused on `solidity` rather than just `hardhat`. Hence the change to the display name.
The description has been updated as well, as all vscode extensions are "for Visual Studio Code".
=> chore: update displayName to `Solidity`

server/src/services/completion/defaultCompletion.ts, server/test/services/completion/completion.ts
Other completions were already available, just missing `msg.sig`
Closes #105
=> chore: add missing `sig` attribute on `msg`

client/src/formatter/forgeFormatter.ts, client/src/formatter/index.ts, client/src/formatter/prettierFormatter.ts, client/src/setup/setupFormatterHook.ts, package.json
Adapting https://github.com/juanfranblanco/vscode-solidity/pull/359 to work with this extension too (h/t @shekhirin)
=> feat: add `forge fmt` option

server/src/parser/analyzer/HardhatProject.ts, server/src/parser/analyzer/NoProject.ts, server/src/parser/analyzer/WorkspaceFileRetriever.ts, server/src/parser/analyzer/nodes/ImportDirectiveNode.ts, server/src/parser/analyzer/resolver/index.ts, server/src/parser/common/types/index.ts, server/src/services/initialization/indexWorkspaceFolders.ts, server/test/helpers/setupMockWorkspaceFileRetriever.ts, server/test/parser/analyzer.ts, server/test/services/validation/hardhatWorker.ts
Hi. Sorry for not opening an issue beforehand. I discussed this with @fvictorio on Discord a bit earlier today and thought I'd go ahead and experiment a bit.
This adds support for `remappings.txt` on a per-project basis. It looks for remappings.txt files beides hardhat config files. 
This is probably not the ideal solution but there's no clear documentation from dapptools or foundry where these remappings files are supposed to be and how they are supposed to be interpreted (e.g. are they supposed to be next to a project config file like hardhat.config, foundry.toml, etc.)? 
Generally, it seems like foundry is actually moving away from remappings.txt towards having those defined in the foundry.toml directly. In that case, the best solution might be to look for foundry.toml files and run …
=> feat(analyzer): add support for remappings.txt

server/src/services/initialization/indexWorkspaceFolders.ts, server/test/services/initialization/indexWorkspaceFolders.ts
This fixes the extension not working on an empty remappings.txt file and also a couple failing tests.
=> fix: extension crashing on empty remappings.txt file

client/src/languageitems/hardhatProject.ts
The command `vscode.open` has better multi-platform support when passing a URI object instead of a path string.
Tested on linux, windows and gitpod.
Closes #227
=> fix: open hardhat.config fails on vscode web (#227)

server/src/services/validation/worker/build/solcCompile.ts
Since we don't have typing for solc output, we missed the case for output.errors being undefined
=> fix: iterating output.errors on undefined

server/src/queries/getOpenDocumentsInProject.ts, server/src/services/validation/validate.ts, server/src/services/validation/worker/build/buildInputsToSolc.ts, server/src/utils/index.ts, server/src/utils/operatingSystem.ts, server/test/services/validation/validation.ts, server/test/solFileDetails/getSolFileDetails.ts, server/test/utils/decodeUriAndRemoveFilePrefix.ts
Closes #264
Starting from a recent version (at least 2.11.2), the list of files resolved from hardhat's GET_DEPENDENCY_GRAPH task have the drive letter as upper case on windows. This made our `buildInputsToSolc` process to fail because string comparison was strict. I added a check to perform a case insensitive comparison on windows systems on this step.
=> fix: validation file name mismatch because of casing on windows

server/src/frameworks/Hardhat/HardhatProject.ts
Worker exit code is not logged on an error line anymore. Additionally, worker status is checked when responding to onWatchedFilesChanged to avoid sending InvalidateCacheMessage to a dead worker.
=> fix: set worker exit code to info and check worker status on watchedFilesChanged

server/src/server.ts, server/src/services/validation/CompilationService.ts, server/src/services/validation/validate.ts, server/src/types.ts
This optimization was lost during the refactor so it's being brought back. It avoids checking/checksumming the compiler on each validation job.
=> optimization: cache solc compiler paths

CHANGELOG.md, package.json, server/src/frameworks/Hardhat/HardhatProject.ts, server/src/server.ts, server/src/services/validation/CompilationService.ts, server/src/services/validation/validate.ts, server/src/types.ts, test/integration/projects/projectless/src/Bar.sol, test/integration/projects/projectless/src/Foo.sol, test/integration/tests/projectless/projectless.test.ts
- Fixed validation with solcjs ([#294](https://github.com/NomicFoundation/hardhat-vscode/issues/294))
- Suppress output channel warnings around worker exit codes ([#298](https://github.com/NomicFoundation/hardhat-vscode/pull/298))
- cache solc compiler paths for all adapters ([#299](https://github.com/NomicFoundation/hardhat-vscode/pull/299))
=> release:2022-12-01

scripts/bundle.js, server/package.json, server/yarn.lock
Closes #305 
By updating the LSP's bundled hardhat to the latest version, we no longer get the related error.
=> maintenance: update hardhat version to latest

server/src/frameworks/Foundry/FoundryProject.ts, server/src/services/validation/CompilationService.ts, server/src/utils/directoryContains.ts, server/test/frameworks/foundry/FoundryProject.test.ts
This change fixes imports on foundry projects where they use paths relative to project root (i.e. `import 'src/MyContract.sol'`). It changes both the import resolution and the solc input as well. For foundry projects, `solcInput.sources` keys are not absolute paths, but paths relative to project root.  (i.e. `'/home/user/myProject/src/Contract.sol' => 'src/Contract.sol'`). This is the only way I found for json-interfaced solc to deal with circular dependencies that use root-relative imports.
=> fix: foundry root imports

coc/src/index.ts, coc/src/vendor/machineId.ts, coc/tsconfig.json, package.json, server/src/analytics/GoogleAnalytics.ts, server/src/analytics/types.ts, server/src/services/initialization/onInitialize.ts, server/src/telemetry/SentryServerTelemetry.ts, server/src/telemetry/types.ts
- Send `Data Source` to google analytics, using the language client's name (`coc.nvim` vs `Visual Studio Code`)
- Send the same value to a new sentry tag `client`
- Send extension version from coc's client (reading it from package.json)
- Generate and send a machineId from coc's client
Coc extension and lsp versions have to be bumped and published.
Closes #320
=> Improve analytics

server/src/services/completion/onCompletion.ts, server/src/services/initialization/indexWorkspaceFolders.ts, server/src/services/initialization/onInitialize.ts, server/src/services/validation/analyse.ts, server/src/services/validation/validate.ts, server/src/telemetry/SentryServerTelemetry.ts, server/src/telemetry/tags.ts, server/src/telemetry/types.ts, server/src/utils/onCommand.ts
All of the places where telemetry transactions are sent (validation, analysis, language server requests) now include a `framework` tag, if it's available for the file under work. Additionally, on the indexing process, extra spans have been added to benchmark with higher granularity, and the project initialization spans have their own framework tag as well (multiple projects can be indexed on a workspace). Tag values are `Hardhat`, `Foundry` and `None`, the last one being for projectless files.
Indexing process spans + framework tag on each:
Tag on requests:
Closes #338
=> chore: add framework to telemetry and improve indexing telemetry

server/README.md, server/package.json
Allow the server to be run at the cli with:
```sh
nomicfoundation-solidity-language-server --stdio
```
The readme has been updated to cover installation and running the language server through neovim's lsp.
Resolves #341.
Build the repo and link the language server:
```sh
yarn build
cd ./server
npm link
nomicfoundation-solidity-language-server --stdio
```
You need to setup neovim. I used the following as my `init.lua`:
```lua
local cmd = vim.cmd
local o = vim.o -- For the globals options
local wo = vim.wo -- For the window local options
local bo = vim.bo -- For the buffer local options
-- ---------------------------------
-- Setup Packer and plugins
-- ---------------------------------
local ensure_packer = function()
local fn = vim.fn
local install_path = …
```
=> feat(server): provide cli invocation

server/src/services/initialization/onInitialize.ts
Fix logic for checking `initializeParams.capabilities.workspace.workspaceFolders` to be `true` before requesting workspace capabilities. Noticed this when investigating #356, althought that behaviour won't change since neovim's client sends `true` anyways.
=> fix: check for workspace folder capability

server/package.json
This moves all dependencies (except `solidity-analyzer`) to devDependencies on the server package. This drastically reduces the installation time of the coc extension and the size from ~180mb to ~20mb.
Closes #373
=> chore: reduce server dependencies

server/src/frameworks/Foundry/FoundryProject.ts, server/src/frameworks/Hardhat/HardhatProject.ts, server/src/frameworks/Hardhat/worker/WorkerProcess.ts, server/src/frameworks/Hardhat/worker/WorkerProtocol.ts, server/src/frameworks/Projectless/ProjectlessProject.ts, server/src/frameworks/base/Project.ts, server/src/parser/analyzer/SolFileEntry.ts, server/src/parser/common/types/index.ts, server/src/services/initialization/indexWorkspaceFolders.ts, server/src/utils/getOrInitialiseSolFileEntry.ts, server/test/frameworks/hardhat/HardhatProject.test.ts
Mark which indexed files are local (i.e. inside configured sources folder), and only analyze those during the initialization step. This avoids e.g. indexing all of OZ contracts when a small project uses few of them.
Closes #302
=> optimization: only analyze local files on initialization

server/src/frameworks/Foundry/FoundryProject.ts, server/src/frameworks/Foundry/getImportCompletions.ts
We are sending the remappings object to solc with absolute paths, e.g:
```
"remappings": [
"ds-test/=/home/.../projects/.../lib/forge-std/lib/ds-test/src/",
"forge-std/=/home/.../projects/.../lib/forge-std/src/",
]
```
After this change, the remappings object is sent in the way they are declared, without transforming relative into absolute paths, e.g:
```
"remappings": [
"ds-test/=lib/forge-std/lib/ds-test/src/",
"forge-std/=lib/forge-std/src/",
]
```
Closes #369
=> fix: remappings structure as solc input

client/CHANGELOG.md, client/README.md, client/docs/publish-extension.md, client/package.json, coc/package.json, package.json, server/package.json
- Optimize initial indexing by only analysing local files ([#302](https://github.com/NomicFoundation/hardhat-vscode/issues/302))
- Reduced deps for coc-solidity ([#373](https://github.com/NomicFoundation/hardhat-vscode/issues/373))
- Mimic foundry solc input mapping ([#377](https://github.com/NomicFoundation/hardhat-vscode/pull/377))
=> chore: bump version to v0.0.10

client/package.json, package-lock.json, server/package.json
The v0.8.18 version of solidity includes supported for named mapping parameters. The `1.1.2` version of `prettier-plugin-solidity` resolves the issue.
Fixes #408.
=> fix: allow formatting of named mapping params

server/src/frameworks/Hardhat/HardhatProject.ts, server/src/frameworks/Hardhat/resolveActionsFor.ts, server/src/frameworks/base/Project.ts, server/src/parser/utils.ts, server/src/services/codeactions/QuickFixResolver.ts, test/protocol/projects/hardhat/contracts/codeAction/ImportConsole.sol, test/protocol/test/textDocument/codeAction/hardhat/codeAction.test.ts
Besides the specific console.sol implementation, a small abstraction was put in place to allow framework adapters to provide quick fixes. Existing quickfixes remain with their current design
Closes #244
=> feat: auto-import console.sol

package-lock.json, server/src/services/documents/onDidChangeWatchedFiles.ts, server/src/services/initialization/indexWorkspaceFolders.ts, server/src/services/initialization/onInitialized.ts, server/src/services/validation/analyse.ts, server/src/services/validation/validate.ts, test/protocol/projects/hardhat/contracts/misc/FileRename.sol, test/protocol/src/TestLanguageClient.ts, test/protocol/test/misc/fileRename.test.ts
I noticed the `didChange` event is fired before the `didWatchedFilesChange`, so files were being analysed/validated without their project being correctly assigned. I moved this assigning to the validate/analysis actions inline, so they are always up to date. Works with new files and renames.
Also included the "clear diagnostics on file delete" task.
Closes #417 
Closes #416 
Closes #387
Closes #310
=> fix: correctly assign project, analyze and validate on new/renamed file

client/CHANGELOG.md, client/package.json, coc/package.json, coc/src/index.ts, package-lock.json, server/package.json, server/scripts/bundle.js
- `Missing content-length header` error on vim-coc extension.
=> chore: bump version to v0.6.14

client/syntaxes/solidity.json
User type names like structs and contracts were not highlighted at all (not only on arrays). With this change, they are highlighted properly in both cases:
Closes #385
=> chore: array syntax highlighting

server/src/utils/WorkspaceFileRetriever.ts
The error happened when there was a file or folder without access permissions while globbing for e.g. config files. It prevented any projects from being indexed at all.
Closes #448
=> fix: suppress access errors while fast-globbing

test/protocol/src/helpers.ts, test/protocol/test/helpers.ts, test/protocol/test/misc/formatting.test.ts, test/protocol/test/textDocument/codeAction/foundry/codeAction.test.ts, test/protocol/test/textDocument/completion/foundry/completion.test.ts, test/protocol/test/textDocument/definition/foundry/definition.test.ts, test/protocol/test/textDocument/implementation/foundry/implementation.test.ts, test/protocol/test/textDocument/publishDiagnostics/foundry/publishDiagnostics.test.ts, test/protocol/test/textDocument/references/foundry/references.test.ts, test/protocol/test/textDocument/rename/foundry/rename.test.ts, test/protocol/test/textDocument/typeDefinition/foundry/typeDefinition.test.ts, test/protocol/test/window/showMessage/foundry/testInitializeError.test.ts
This change involves checking whether foundry is installed when attempting to run protocol tests that involve forge. On mac and windows, if forge is not available, tests will be skipped. On linux they will always be run.
Closes #459
=> chore: fix  failing tests on mac CI build

README.md, client/README.md, client/README.template.md, coc/README.md, docs/features.md, server/README.md
Document the support experimental projects: Foundry, Truffle and Ape.
Update our formatting section to include `forge fmt`.
=> docs: add Project sections to docs

server/scripts/bundle.js
Changed the target on esbuild to node14. By default it is `esnext`.
Manually ran protocol tests on node 14 and they are passing
=> chore: support node 14

server/src/services/formatting/forgeFormat.ts, server/src/services/formatting/onDocumentFormatting.ts
This will help us troubleshoot issues with formatting. Setting the log level to 'verbose' right now gives us some information like the formatting input and the output, but we can't tell which formatter was invoked.
This change adds tracing to show what formatter is used, what binary in the case of forge, and in which directory it's invoked.
References #456
=> chore: add tracing to document formatting

server/src/services/formatting/forgeFormat.ts, server/src/services/formatting/onDocumentFormatting.ts
This changes how `forge fmt` is invoked from the server on a document formatting request. I replace the use of `execSync` with `exec`, so the server can continue handling other requests while forge is running, and I also added a 2 seconds timeout for the process. If it times out, an error will be logged on the output channel.
References #462
=> fix: make forge fmt call async and set a timeout

server/src/frameworks/Ape/ApeProject.ts, server/src/frameworks/Foundry/FoundryProject.ts, server/src/frameworks/Truffle/TruffleProject.ts, server/src/services/initialization/indexWorkspaceFolders.ts
This is to address the new errors appearing on sentry related to project initialization. I just realized that our logger creates error entries when we call the `.error` method. I replaced existing logging related to project initialization from `error` calls to `info`, to avoid this.
=> chore: stop capturing initialize errors

server/src/frameworks/Foundry/FoundryProject.ts, test/protocol/projects/foundry/remappings.txt, test/protocol/projects/foundry/src/definition/Importer.sol, test/protocol/test/textDocument/completion/foundry/completion.test.ts, test/protocol/test/textDocument/definition/foundry/definition.test.ts
Replaced `path.join` with `path.resolve` when parsing remappings to allow for absolute path remappings.
Closes #476
=> fix: support absolute path remappings on foundry projects

client/scripts/bundle.js, server/scripts/bundle.js, server/src/frameworks/Hardhat/HardhatProject.ts, server/src/frameworks/Hardhat/worker/WorkerProcess.ts, server/src/frameworks/Truffle/ConfigLoader.ts, server/src/frameworks/Truffle/TruffleProject.ts
Load truffle config on child processes to avoid unhandled errors
Closes #492
=> Unhandled exceptions

server/src/services/documents/onDidChangeWatchedFiles.ts
Even though I couldn't reproduce the issue, I'm confident that the cause is a change introduced in 0.6.13 (when the issue first appeared), in which deleted files are removed from the sol file index. My guess is that after being removed, some debounced analyze/validate requests hit and the entry is not there anymore. The logic in place will try to index the file but since it was deleted it should be failing. 
This fix just stops removing the sol file entry on file deletion. That removal was in place just to free up some memory, but it's negligible.
Closes #487
=> fix: uri not indexed error

docs/publish-extension.md
Our changes to the build to pull in telemetry secrets for ga and sentry clashed with our publish instructions (to `git clean` to test that there are no changes with an `npm install`).
A warning to check that a valid `.env` file has been added is included now in the publish doc.
=> docs: add .env warning to publish instructions

.github/workflows/add-issue-to-project.yml, .github/workflows/add-label-to-new-issue.yml, .github/workflows/ci.yaml, client/src/popups/showAnalyticsAllowPopup.ts, package-lock.json, package.json, test/runTests.ts
As the version we request is already deprecated:
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default
=> update NodeJS version used in CI

.github/workflows/ci.yaml, client/package.json, package-lock.json, package.json, test/e2e/tests/commands/clean.test.ts, test/runTests.ts
This is required since we will not bundle Slang, requiring at least GLIBC 2.28, see https://github.com/NomicFoundation/slang/pull/909.
=> Bump required VS Code version to ^1.86

server/package.json
The run of `npm pack` was not picking up `./out/**` subfolders. The `files` property has now been changed to include the entire folder.
Fixes #558.
=> fix(server): rework server package file inclusion

server/src/parser/slangHelpers.ts, server/src/services/documentSymbol/onDocumentSymbol.ts, server/src/services/semanticHighlight/onSemanticTokensFull.ts
This is arguably more useful approach - we designed our parser to be error-tolerant and it makes more sense to offer slightly incomplete experience rather than just suddenly turning off all features just because the user is using a slightly newer version that may not get full coverage.
=> feat: Use the latest version support by Slang even if not resolved

client/CHANGELOG.md, client/package.json, coc/package.json, flags.json, server/package.json, server/src/parser/slangHelpers.ts, server/src/services/documentSymbol/onDocumentSymbol.ts, server/src/services/semanticHighlight/onSemanticTokensFull.ts
- Run Semantic Highlighting and document symbols on later solc versions not yet support by the Slang parser (behind feature flag) ([562](https://github.com/NomicFoundation/hardhat-vscode/pull/562))
=> release: 0.8.2

.github/workflows/add-label-to-new-issue.yml
Update the labelling workflow to bring in the latest additions from Hardhat.
The update:
* Updates to `github-script@v7`
* Switches from `pull_request` to `pull_request_target`, this should resolve failures from external PRs, note however this has security implications - though the same tradeoff we have made in Hardhat
* Add a retry
=> chore: update labelling workflow

client/language-configuration.json, docs/publish-extension.md
---
This PR introduces support for region comments within Solidity `.sol` files previously mentioned in https://github.com/NomicFoundation/hardhat-vscode/issues/452, addressing the issue where developers were seeking the ability to organize code into collapsible sections for improved readability and navigation. 
- Modified the Solidity language configuration file to recognize the `//#region` and `//#endregion` patterns.
Region comments are implemented by modifying the Solidity language grammar to include start and end region markers. The pattern follows the typical convention of `//#region` and `//#endregion` which is familiar to developers from other programming languages.
```solidity
//#region ExampleRegion
// Your Solidity code here
//#endregion ExampleRegion
```
The language …
=> feat: add support for region comments

package-lock.json, server/package.json
This pulls in support for latest Solidity 0.8.25 and contains a bugfix that allows to correctly parse `f.address` for function pointers in the assembly; other than that, it's passing Sanctuary tests for mainnet and popular L2s like Arbitrum, BSC, Polygon or Optimism.
Hopefully this will get rid of the "Unsupported version" errors in Sentry that we were receiving lately; also the language coverage should be fairly complete now.
=> Bump Slang to 0.14.2

client/package.json, client/syntaxes/solidity-markdown-injection.json
---
I added markdown syntax support that was requested based on the description from here https://github.com/NomicFoundation/hardhat-vscode/issues/572
I made sure to disable any solidity extension to recreate it
After applying changes, while plugins are disabled
=> chore: Add markdown syntax support - Issue 572

client/syntaxes/solidity.json
The duplicate entry is invalid JSON. Looks like the duplicate was added a while back in #169
=> remove duplicate natspec syntax highlighter

flags.json
After the [v0.8.4](https://github.com/NomicFoundation/hardhat-vscode/releases/tag/v0.8.4) release with the latest Slang fixes, we can now bump up the release flags to 20%.
=> set Slang release flags to 20%

server/src/parser/slangHelpers.ts
converted to an `info()` level statement, to reduce noise in error reports.
=> remove pragma version error

flags.json
After the https://github.com/NomicFoundation/hardhat-vscode/releases/tag/v0.8.5 release with the latest Slang fixes, we can now bump up the release flags to 50%.
=> set Slang release flags to 50%

flags.json
No new issues or bug reports. Let's do it 🚀
Btw, I noticed that the terminology in the file is now a bit confusing. `percent: 1` reads like 1% rather than 100% 🤔 but I don't think it is worth the risk to change it now, considering the implications for existing/older versions still running.
=> set Slang release flags to 100%

.github/workflows/ci.yaml, package-lock.json, server/package.json
Switch to an explicit github action for uploading code coverage files to codecov. We move away from the npm package inline with codecov docs: https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage.
=> chore: update CI uploading of codecov

client/CHANGELOG.md, docs/codebase.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "langauge" to "language".
Corrected "intialization" to "initialization".
Corrected "wether" to "whether".
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files

client/scripts/bundle.js
We include syntax support for Solidity embedded within markdown. However our build was not including the syntax file. This has been fixed in the extensions bundling script.
=> fix: package should include markdown syntax

server/src/frameworks/Foundry/resolveForgeCommand.ts
---
This PR adds support for `foundryup` on Windows, especially if `forge` is not available in `path` or conflicts with other globally installed packages.
=> Add `foundryup` support for Windows

.github/codecov.yml, .github/workflows/ci.yaml, server/src/services/formatting/onDocumentFormatting.ts
Formatting has moved to the server side. We have added Sentry transaction monitoring to the top level `onDocumentFormatting` call.
There are separate subspans on the Sentry transaction for Forge and Prettier.
Resolves #622.
=> chore: add Sentry transaction monitoring to formatting

server/src/compilerDiagnostics/diagnostics/SpecifyVisibility.ts, server/test/services/codeactions/specifyVisibility.ts, test/protocol/test/textDocument/codeAction/hardhat/codeAction.test.ts
I fixed a typo in the SpecifyVisibility.ts file, correcting the word "visibilty" to "visibility" in the title property of an object.
Specific Change:
Before:
title: "Add ${visibility} visibilty to function declaration",
After:
title: "Add ${visibility} visibility to function declaration",
This change ensures proper spelling of "visibility," improving code clarity and reducing potential confusion.
=> Typo fix in Title Update SpecifyVisibility.ts

client/README.md
I fixed a typo in the README.md file, specifically in the alt text of an image link.
Changes Made:
Before:
"Confiure default formatter"
After:
"Configure default formatter"
This involved one addition and one deletion, ensuring the alt text is now correctly spelled.
=> Fix typo in the link Update README.md

client/src/extension.ts, client/src/popups/showSoliditySurveyPopup.ts
---
This is a follow-up to https://github.com/NomicFoundation/hardhat/pull/6133
It adds the solidity survey popup similarly to how it was done in https://github.com/NomicFoundation/hardhat-vscode/pull/312
=> chore: add the solidity survery 2024 popup

.github/codecov.yml, .github/workflows/ci.yaml, client/CHANGELOG.md, client/README.md, client/package.json, client/src/extension.ts, client/src/popups/showSoliditySurveyPopup.ts, coc/package.json, package-lock.json, server/package.json, server/src/compilerDiagnostics/diagnostics/SpecifyVisibility.ts, server/src/frameworks/Foundry/resolveForgeCommand.ts, server/src/services/formatting/onDocumentFormatting.ts, server/test/services/codeactions/specifyVisibility.ts, test/protocol/test/textDocument/codeAction/hardhat/codeAction.test.ts
- Add Solidity Survey 2024 popup ([#625](https://github.com/NomicFoundation/hardhat-vscode/pull/625))
- Scan additional `forge` path on Windows for formatting commands, thanks @akshatmittal ([#515](https://github.com/NomicFoundation/hardhat-vscode/pull/515))
- Add telemetry diagnostics around formatting ([#622](https://github.com/NomicFoundation/hardhat-vscode/issues/622))
=> Release 2025-01-14

client/README.template.md
We only updated the output previously.
=> docs: update the template to fix the spelling mistake

.github/codecov.yml, server/src/frameworks/Foundry/resolveForgeCommand.ts, server/src/services/formatting/forgeFormat.ts, server/src/services/formatting/onDocumentFormatting.ts, server/src/utils/errors.ts, server/src/utils/operatingSystem.ts
This PR changes the handling of the child process spawned when running `forge`, currently only used for formatting. The broken EPIPE error happens when a process tries to write to the stdin of a dead process.
=> Rework forge command invocation (broken EPIPE issue)

client/src/telemetry/SentryClientTelemetry.ts, server/scripts/bundle.js, server/src/eventEmitterPatch.ts, server/src/index.ts
Patch `EventEmitter` `init` and `emit` functions to pick up stack traces and append them as breadcrumbs on process' uncaught exceptions. This is an effort to have more context on unhandled EPIPE errors
=> chore: add breadcrumbs to sentry events on uncaught error events

server/src/frameworks/Hardhat/Hardhat3/Hardhat3Project.ts, server/src/services/validation/validate.ts, test/protocol/projects/hardhat3/contracts/workspace/onDidChangeWatchedFiles/ConfigReloadTest.sol, test/protocol/src/TestLanguageClient.ts, test/protocol/test/workspace/didChangeWatchedFiles/hardhat3.test.ts
This PR introduces a change where events on the hardhat.config file are listened and the project is reinitialized accordingly (e.g. changes to paths, remappings, etc), without needing to restart the extension.
The main blocker for this was that ESM module imports are cached, so after the first initialization, when attempting to re-import the hardhat.config file (through `importUserConfig` helper from hardhat), it was returning the cached content. The workaround I chose for this was to create a copy of the config file whenever we want to load it, load the copy, and then delete it. A better solution would be possible if we were able to pass the URI of the config file to the `importUserConfig` helper, instead of path, because we could append a random query string to the URI and it would skip …
=> Hardhat 3 config reload support

server/src/telemetry/SentryServerTelemetry.ts, server/src/telemetry/anonymization.ts, server/test/telemetry/anonymization.ts
Closes #485 
All potential user-identifying information that may be present in error events or performance traces are now scrubbed before being sent to Sentry.
File paths and URLs are replaced with `<user_file>` strings. For the extension's internal files, we scrub up to the the extension root path, and keep the internal file subpath for debugging purposes. This will result in paths looking like `<extension_root>/server/out/index.js`. This detection of internal files additionally is only applied to `.js` files, so we default on the safe side of scrubbing most file paths (which include .sol files).
Additionally some default fields that may be populated by the SDK are cleared as well:
- User email
- User name
- Server name
Some fields may differ from what has been specified in the design …
=> Sentry event anonymization

client/src/telemetry/SentryClientTelemetry.ts, client/src/telemetry/anonymization.ts
Duplicated server anonimization logic. We may get rid of this duplication once we set up a monorepo structure
=> Sentry event anonymization for extension client

server/src/frameworks/Hardhat/Hardhat2/getImportCompletions.ts, server/src/services/completion/getImportPathCompletion.ts
If the import completion is triggered by deleting a quote on an existing import and readding it then, the position is the start of the import but we delete the entire length of the import line which creates a negative position triggering the bug.
Instead, we short circuit. If the import is already the suggestion we don't suggest it again.
Fixes #150.
=> fix: range create error
