NomicFoundation/hardhat-vscode

server/src/parser/services/validation/SolidityValidation.ts

Log validation timeouts as errors, but suppress the kill signal errors.
Resolves HHVSC-110

chore(validation): improve logging

---

.changeset/fluffy-socks-vanish.md
server/src/compilerDiagnostics/compilerDiagnostics.ts
server/src/compilerDiagnostics/diagnostics/ContractCodeSize.ts
server/test/parser/services/validation/testData/ContractCodeSize.sol
server/test/parser/services/validation/validation.ts

We don't provide any quickfixes (we can't make your contract smaller),
but we do constain the warning to just the contract name.
Resolves #129.
Linear HHVSC-118

feat(validation): constrain 5574 to contract name

---

.changeset/wild-paws-travel.md
CHANGELOG.md
client/src/telemetry/SentryClientTelemetry.ts
package.json
server/src/index.ts
server/src/telemetry/SentryServerTelemetry.ts

- Change to telemetry, to stop capturing unhandled exceptions on the client ((#156)[https://github.com/NomicFoundation/hardhat-vscode/issues/156])

release: 2022-04-01

---

client/src/formatter/index.ts
client/src/telemetry/SentryClientTelemetry.ts

We have see no errors except expected parser errors, so lets suppress the formatting errors.

chore(client): suppress formatter errors

---

server/src/services/signaturehelp/onSignatureHelp.ts

We are getting sentry exceptions from signatures that aren't parsed. We don't have enough information to go on so are pulling in the definition node type.
Part of #174
Linear: HHVSC-148

chore(signature): better logging on parsing

---

.github/workflows/ci.yaml
package.json
server/package.json
server/yarn.lock

Add codecov command to be run in the build.

chore: add codecov

---

server/src/services/validation/HardhatWorker.ts

A validation worker process that exits with an error code should be
restarted.
In support of this, open jobs against the worker are cancelled.

fix: restart worker process on unexepected exit

---

CHANGELOG.md
package.json
server/src/services/validation/HardhatWorker.ts
server/src/services/validation/compilerProcessFactory.ts
server/src/services/validation/validate.ts
server/src/services/validation/worker.ts
server/src/services/validation/worker/initialiseWorkerState.ts
server/src/types.ts
server/test/services/validation/hardhatWorker.ts
server/test/services/validation/validation.ts

- Fix for restarts on invalid hardhat configs ([#212](https://github.com/NomicFoundation/hardhat-vscode/pull/212))

release:2022-07-21

---

CHANGELOG.md
language-configuration.json
package.json
test/integration/client.ts
test/integration/common/assertLspCommand.ts
test/integration/helpers/assertions.ts
test/integration/helpers/commands.ts
test/integration/helpers/docPaths.ts
test/integration/helpers/files.ts
test/integration/helpers/joinLines.ts
test/integration/helpers/sleep.ts
test/integration/tests/definition/definition.test.ts
test/integration/tests/implementation/implementation.test.ts
test/integration/tests/language-configuration/onEnterRules.test.ts
test/integration/tests/references/references.test.ts
test/integration/tests/rename/rename.test.ts
test/integration/tests/typedefinition/typedefinition.test.ts

- Added auto-insert of intermediary stars in block comments ([#75](https://github.com/NomicFoundation/hardhat-vscode/issues/75))

release:2022-08-04

---

server/src/compilerDiagnostics/diagnostics/AddMultiOverrideSpecifier.ts
server/src/compilerDiagnostics/diagnostics/common/resolveInsertSpecifierQuickFix.ts
server/test/services/codeactions/addMultioverrideSpecifier.ts
server/test/services/codeactions/testData/AddMultioverrideSpecifier.sol

feat: Quickfix for partially-specified multi override

---

server/src/compilerDiagnostics/compilerDiagnostics.ts
server/src/compilerDiagnostics/diagnostics/AddLicenseIdentifier.ts
server/test/services/codeactions/addLicenseIdentifier.test.ts
server/test/services/codeactions/testData/AddLicenseIdentifier.sol
snippets/solidity.json

QuickFix for missing license identifier on contracts

---

.github/workflows/ci.yaml
test/integration/helpers/files.ts

Add caching to github action ci jobs

---

.github/workflows/ci.yaml
CHANGELOG.md
client/src/popups/setupIndexingHooks.ts
docs/publish-extension.md
package.json
server/src/compilerDiagnostics/compilerDiagnostics.ts
server/src/compilerDiagnostics/diagnostics/AddLicenseIdentifier.ts
server/src/compilerDiagnostics/diagnostics/AddMultiOverrideSpecifier.ts
server/src/compilerDiagnostics/diagnostics/common/resolveInsertSpecifierQuickFix.ts
server/src/services/initialization/onInitialized.ts
server/src/services/validation/HardhatWorker.ts
server/src/services/validation/compilerProcessFactory.ts
server/src/types.ts
server/test/services/codeactions/addLicenseIdentifier.test.ts
server/test/services/codeactions/addMultioverrideSpecifier.ts
server/test/services/codeactions/addOverrideSpecifier.ts
server/test/services/codeactions/addVirtualSpecifier.ts
server/test/services/codeactions/asserts/assertCodeAction.ts
server/test/services/codeactions/constrainMutability.ts
server/test/services/codeactions/markContractAbstract.ts
server/test/services/codeactions/specifyVisibility.ts
server/test/services/codeactions/testData/AddLicenseIdentifier.sol
server/test/services/codeactions/testData/AddMultioverrideSpecifier.sol
server/test/services/validation/hardhatWorker.ts
snippets/solidity.json
test/integration/helpers/files.ts

- Added quickfix for partially-specified multi override contract functions ([#50](https://github.com/NomicFoundation/hardhat-vscode/issues/50))
- Added quickfix for missing license identifier ([#26](https://github.com/NomicFoundation/hardhat-vscode/issues/26))
- Fix open files not being analyzed because of validator not being ready ([#229](https://github.com/NomicFoundation/hardhat-vscode/issues/229))

Release:2022-08-18

---

server/src/services/validation/convertHardhatErrorToDiagnostic.ts
server/src/types.ts
server/test/services/validation/convertHardhatErrorToDiagnostic.ts

feat: diagnostic for hardhat error 411 - library not installed

---

docs/publish-extension.md

Update the publish commands with better examples.

docs: add clearer publish commands

---

client/src/commands/Command.ts
client/src/commands/InsertSemicolonCommand.ts
client/src/setup/setupCommands.ts
package.json
server/src/services/completion/getImportPathCompletion.ts
server/src/services/completion/onCompletion.ts
server/src/services/initialization/onInitialize.ts
server/test/server.ts
server/test/services/completion/imports.ts
test/integration/index.ts
test/integration/tests/codeactions/addLicenseIdentifier.test.ts
test/integration/tests/codeactions/addMultiOverrideSpecifier.test.ts
test/integration/tests/codeactions/addOverrideSpecifier.test.ts
test/integration/tests/codeactions/addPragmaVersion.test.ts
test/integration/tests/codeactions/addVirtualSpecifier.test.ts
test/integration/tests/codeactions/constrainMutability.test.ts
test/integration/tests/codeactions/markAbstract.test.ts
test/integration/tests/codeactions/specifyVisibility.test.ts
test/integration/tests/commands/clean.test.ts
test/integration/tests/commands/flatten.test.ts
test/integration/tests/completion/completion.test.ts
test/integration/tests/configuration/configuration.test.ts
test/integration/tests/definition/definition.test.ts
test/integration/tests/diagnostics/diagnostics.test.ts
test/integration/tests/implementation/implementation.test.ts
test/integration/tests/references/references.test.ts
test/integration/tests/remappings/remappings.test.ts
test/integration/tests/rename/rename.test.ts
test/integration/tests/typedefinition/typedefinition.test.ts

Closes #104 
When accepting a completion from imports, a semicolon will be appended if the current line doesn't end with a semicolon already.

feat: auto insert semicolon on import completion

---

server/src/services/validation/CompilationService.ts
test/integration/client.ts
test/integration/helpers/assertions.ts
test/integration/index.ts
test/integration/tests/completion/completion.test.ts
test/integration/tests/projectless/projectless.test.ts

This change makes the compilation 3x-10x faster, specially for hardhat projects.
TBD if this has any negative implication

optimization: disable optimizer and outputSelection

---

server/src/services/completion/defaultCompletion.ts
server/test/services/completion/completion.ts
test/protocol/projects/hardhat/contracts/completion/Globals.sol
test/protocol/test/textDocument/completion/hardhat/completion.test.ts

chore: add new abi.encodeCall to completions

---

server/src/services/validation/analyse.ts
server/src/services/validation/validate.ts

chore: track timing for analysis

---

server/src/services/validation/DiagnosticConverter.ts

fix: foundry validation broken on windows

---

server/src/telemetry/SentryServerTelemetry.ts
server/src/telemetry/sentryEventFilter.ts

chore: filter out unwanted sentry events

---

client/src/formatter/forgeFormatter.ts
client/src/utils/os.ts
server/src/frameworks/Foundry/FoundryProject.ts

fix: improve forge binary lookup

---

README.md
coc/README.md

chore: docs for coc.nvim users

---

client/src/formatter/forgeFormatter.ts
client/src/utils/os.ts

chore: cache resolved forge path on client

---

server/src/services/initialization/indexWorkspaceFolders.ts

optimization: initialize projects sequentially

---

client/CHANGELOG.md
client/package.json
client/src/formatter/forgeFormatter.ts
client/src/utils/os.ts
coc/package.json
package-lock.json
server/package.json
server/src/services/initialization/indexWorkspaceFolders.ts

- improve forge fmt speed through caching ([#380](https://github.com/NomicFoundation/hardhat-vscode/issues/380))
- throttle project initalization to cap max cpu usage ([#389](https://github.com/NomicFoundation/hardhat-vscode/issues/389))

release: v-0.6.11

---

client/src/setup/setupValidationJobHooks.ts

Right now we only trigger validation on file change, and there are many cases where a file is not valid e.g. because dependencies are not installed. Since we cannot get file watchers for dependencies, this change attempts to fix the issue and will trigger validation on a text document when changing focus

Chore: trigger validation on focused editors to avoid stale validation status

---

package-lock.json
server/package.json
server/src/frameworks/Hardhat/HardhatProject.ts
server/src/services/initialization/onInitialized.ts
server/src/services/signaturehelp/onSignatureHelp.ts
server/src/services/validation/analyse.ts
server/src/services/validation/validate.ts

Update the node language server dependencies. Some types have changed and so functions are converted to async.

chore: update node-languageserver version

---

docs/publish-extension.md

Just a few fixes on the publish docs to match the new monorepo structure

chore: update the publish docs

---

client/syntaxes/solidity.json

chore: highlight user-defined value types

---

client/README.md
client/README.template.md
client/package.json
client/scripts/bundle.js
client/src/setup/setupExtensionState.ts
coc/README.md
coc/README.template.md
coc/package.json
coc/src/index.ts
server/README.md
server/README.template.md
server/package.json

chore: update namespace from @ignored to @nomicfoundation

---

.vscode/launch.json
client/src/setup/setupExtensionState.ts
server/src/utils/index.ts
test/protocol/package.json
test/runTests.ts

chore: replace NODE_ENV to VSCODE_NODE_ENV to avoid clashes

---

client/README.md
docs/features.md
docs/publish-extension.md
server/README.md

Fix: typos

---

server/src/frameworks/Truffle/TruffleProject.ts

fix: move npm root to try/catch block and make it async

---

client/CHANGELOG.md
client/package.json
coc/package.json
docs/publish-extension.md
package-lock.json
server/package.json

- Issue with missing telemetry code ([#501](https://github.com/NomicFoundation/hardhat-vscode/pull/501))

release: 2023-06-01

---

server/test/services/navigation/definition.ts

fix a typo: `statment`->`statement` 
---

chore: fix typos

---

.github/workflows/review-requested-slack-notification.yml
.github/workflows/review-submitted-slack-notification.yml

This PR adds the Slack DMs workflows that notify about reviews

Add slack DMs workflows

---

flags.json

Testing the flags are working correctly. I will revert this afterwards.

experiment: turn off Slang feature flags

---

docs/publish-extension.md

update release docs

---

README.md

Hello. Changing the name and link to the social network in the documentation
---

Docs: Changing the name and link to the social network

---

package-lock.json
server/package.json

Revert to versions of previous release

chore: revert vscode-languageserver to 8.1.0

---

client/src/setup/setupLanguageServerHooks.ts
server/src/analytics/GoogleAnalytics.ts
server/src/analytics/types.ts
server/src/services/initialization/onInitialize.ts
server/src/telemetry/SentryServerTelemetry.ts
server/src/telemetry/types.ts

Besides this change, I already setup the custom dimension on our GA4 property

Tag vscode version on google analytics

---

package-lock.json
server/package.json
server/src/frameworks/Hardhat/Hardhat3/Hardhat3Project.ts
test/protocol/projects/hardhat3/package.json
test/protocol/projects/hardhat3/pnpm-lock.yaml

Now supports hardhat 3 projects with version >= next.24

Adapt to new getCompilationJobs api
